const accounts = [
  {
    id: 1,
    title: "Red Scarf Girl: A Memoir of the Cultural Revolution",
    author: "Ji-li Jiang",
    description: "A 12-year-old girl from Shanghai documents her family's persecution during the Cultural Revolution. She witnesses her family's persecution and faces the dilemma of choosing loyalty to family or to the Communist Party. Her younger siblings are separated from her, and her father is imprisoned.",
    yearPublished: 1997,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/413432.Red_Scarf_Girl",
    amazon: "https://www.amazon.com/Red-Scarf-Girl-Cultural-Revolution/dp/0064462080"
  },
  {
    id: 2,
    title: "The Cowshed: Memories of the Chinese Cultural Revolution",
    author: "Ji Xianlin",
    description: "A renowned Peking University professor imprisoned for nine months in a \"cowshed\" (detention center on campus). Documents torture, forced labor, and struggle sessions. The professor is persecuted by his own students and colleagues.",
    yearPublished: 1998,
    country: "China / United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/en/book/show/25387260-the-cowshed",
    amazon: "https://www.amazon.com/Cowshed-Memories-Chinese-Cultural-Revolution/dp/1590179269"
  },
  {
    id: 3,
    title: "Life and Death in Shanghai",
    author: "Nien Cheng",
    description: "A 51-year-old woman imprisoned in solitary confinement for 6.5 years. Arrested as an alleged 'foreign spy' for her education in London and work for Shell Oil. Her daughter was killed by Red Guards for refusing to denounce her mother.",
    yearPublished: 1986,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/537404.Life_and_Death_in_Shanghai",
    amazon: "https://www.amazon.com/Life-Death-Shanghai-Cheng-Nien/dp/0802145167"
  },
  {
    id: 4,
    title: "Red Azalea: A Memoir",
    author: "Anchee Min",
    description: "Born 1957 in Shanghai, Min was a Little Red Guard at age 5–6. At age 17, sent to a labor collective, then selected for Madame Mao's propaganda film studio as an actress. Details indoctrination of children and forced participation in propaganda.",
    yearPublished: 1994,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/92936.Red_Azalea",
    amazon: "https://www.amazon.com/Red-Azalea-Anchee-Min/dp/1400096987"
  },
  {
    id: 5,
    title: "Red Sorrow: A Memoir of the Cultural Revolution",
    author: "Nanchu",
    description: "At age 13, witnesses Red Guards arrest and torture her parents. Left to care for younger brother while outcast from society in Shanghai. Sent to military-labor camp on the Sino-Soviet border. Describes the experience of an entire generation.",
    yearPublished: null,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/25159285",
    amazon: "https://www.amazon.com/Red-Sorrow-Memoir-Cultural-Revolution/dp/1628725869"
  },
  {
    id: 6,
    title: "The Secret Piano: From Mao's Labor Camps to Bach's Goldberg Variations",
    author: "Zhu Xiao-Mei",
    description: "A pianist imprisoned in Cultural Revolution labor camps. Documents how music and art served as resistance and survival.",
    yearPublished: 2003,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/12340404-the-secret-piano",
    amazon: "https://www.amazon.com/Secret-Piano-Labor-Goldberg-Variations/dp/1611090776"
  },
  {
    id: 7,
    title: "Wild Swans: Three Daughters of China",
    author: "Jung Chang",
    description: "A multigenerational family memoir spanning grandmother (concubine), mother (Communist revolutionary), and author through the CR period. Shows the impact across generations and changing political contexts.",
    yearPublished: 1991,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/1848.Wild_Swans",
    amazon: "https://www.amazon.com/Wild-Swans-Three-Daughters-China/dp/0743246985"
  },
  {
    id: 8,
    title: "Forbidden Memory: Tibet during the Cultural Revolution",
    author: "Tsering Woeser",
    description: "First-hand account of the Cultural Revolution's impact specifically on Tibetan intellectuals and religious figures, documenting persecution of Tibetan cultural and religious leaders.",
    yearPublished: 2006,
    country: "United States / Tibet",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/50878473-forbidden-memory",
    amazon: "https://www.amazon.com/Forbidden-Memory-during-Cultural-Revolution/dp/1612349692"
  },
  {
    id: 9,
    title: "The Little Red Guard: A Family Memoir",
    author: "Wenguang Huang",
    description: "A family memoir showing how one family attempted to practice traditional funeral rites and honor a dying grandmother despite Communist bans during the CR. Documents resistance to state control over private and family life.",
    yearPublished: 2012,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/13114766-the-little-red-guard",
    amazon: "https://www.amazon.com/Little-Red-Guard-Family-Memoir/dp/1594486557"
  },
  {
    id: 10,
    title: "Chinese Cinderella: The True Story of an Unwanted Daughter",
    author: "Adeline Yen Mah",
    description: "Primarily about early life, this memoir includes accounts of the author's experiences during the Cultural Revolution in China. Documents family persecution.",
    yearPublished: 1997,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/82751.Chinese_Cinderella",
    amazon: "https://www.amazon.com/Chinese-Cinderella-Story-Unwanted-Daughter/dp/0385740077"
  },
  {
    id: 11,
    title: "Red China Blues: My Long March from Mao to Now",
    author: "Jan Wong",
    description: "A Canadian-Chinese journalist's account of living through the CR as a Western-educated woman who arrived as a Maoist true believer. Documents struggle sessions, labor assignments, and gradual disillusionment leading to journalism.",
    yearPublished: 1996,
    country: "United States / Canada",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/1502744.Red_China_Blues",
    amazon: "https://www.amazon.com/Red-China-Blues-Long-March/dp/0385482329"
  },
  {
    id: 12,
    title: "Bend, Not Break: A Life in Two Worlds",
    author: "Ping Fu",
    description: "Childhood during the CR, separation from family, experiences in exile and labor camps. Eventually escaped to the United States and founded a tech company.",
    yearPublished: 2012,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/15811544-bend-not-break",
    amazon: "https://www.amazon.com/Bend-Not-Break-Life-Worlds/dp/1591845521"
  },
  {
    id: 13,
    title: "The Execution of Mayor Yin and Other Stories from the Great Proletarian Cultural Revolution",
    author: "Chen Ruoxi",
    description: "Fictionalized short stories by Chen Ruoxi (Chen Jo-Hsi) based on her lived experience returning to China and witnessing the CR firsthand. One of the earliest literary accounts to reach Western readers. Published as a story collection.",
    yearPublished: 1978,
    country: "United States",
    category: "Literary Fiction",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/658565.The_Execution_of_Mayor_Yin_and_Other_Stories_from_the_Great_Proletarian_Cultural_Revolution",
    amazon: "https://www.amazon.com/Execution-Stories-Proletarian-Cultural-Revolution/dp/0253216907"
  },
  {
    id: 14,
    title: "Confessions: An Innocent Life in Communist China",
    author: "Kang Zhengguo",
    description: "Attempted to obtain a copy of Doctor Zhivago during the CR. Arrested and sentenced to a rural labor reeducation camp. Documents the severity of persecution for minor acts of intellectual curiosity.",
    yearPublished: 2007,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/1052379.Confessions",
    amazon: "https://www.amazon.com/Confessions-Innocent-Life-Communist-China/dp/0393332004"
  },
  {
    id: 15,
    title: "The Good Women of China: Hidden Voices",
    author: "Xinran (with Esther Tyldesley)",
    description: "A collection of interviews and testimonies from Chinese women about their CR experiences. Xinran, herself a CR survivor, documents female perspectives on persecution and survival.",
    yearPublished: 2002,
    country: "United States",
    category: "Oral History",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/178796.The_Good_Women_of_China",
    amazon: "https://www.amazon.com/Good-Women-China-Hidden-Voices/dp/1400030803"
  },
  {
    id: 16,
    title: "CR/10 Project (Cultural Revolution: 10)",
    author: "University of Pittsburgh East Asian Library",
    description: "Oral history project initiated 2015. Contains 300+ video interviews of 10 minutes each with individuals who experienced the CR. Interviews conducted in Chinese with English subtitles, collected in USA, China, Canada, and other countries. Each interviewee was asked: \"What was most memorable about your experience during the CR?\" Ongoing project.",
    yearPublished: 2015,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://digital.library.pitt.edu/collection/chinas-cultural-revolution-memories-the-CR10-project",
    goodreads: null,
    amazon: null
  },
  {
    id: 17,
    title: "Down to the Countryside Movement Collection",
    author: "Dartmouth Library (curators: Nien Lin Xie, Ding Ye)",
    description: "Dartmouth Library collection of primary sources from 17 million 'sent-down youth' or 'rusticated youth' relocated 1968–1978 to remote villages. Contains diaries, letters, photographs, manuscripts, and artifacts. Nearly 300,000 digitized items.",
    yearPublished: 2016,
    country: "United States",
    category: "Archival Collection",
    url: "https://www.library.dartmouth.edu/digital/digital-collections/down-countryside-movement",
    goodreads: null,
    amazon: null
  },
  {
    id: 18,
    title: "\"Life Starts at Sixteen\" Memoir by Liu Ping",
    author: "Liu Ping",
    description: "Liu Ping was sent to Inner Mongolia in 1969 at age 16. Manuscript written in 1994 describing 5 years (1969–1974) as rusticated youth. Her father committed suicide during CR persecution; she was labeled 'child who could be educated and transformed.' Details physical labor, hardship, constant surveillance. Diaries from 1969–1972 are also preserved.",
    yearPublished: 1994,
    country: "China / United States",
    category: "Memoir",
    url: "https://collections.dartmouth.edu/teitexts/rusticated-youth-tei/diplomatic/Life_starts_at_Sixteen-diplomatic.html",
    goodreads: null,
    amazon: null
  },
  {
    id: 19,
    title: "The Revolution They Remember (Documentary Film)",
    author: "University of Pittsburgh East Asian Library & Dartmouth College Library",
    description: "Feature-length documentary (produced 2019–2020) featuring interviews from the CR/10 Project and Dartmouth's Down to the Countryside Movement collection. Includes archival footage, photographs, and scholarly commentary. Free online streaming.",
    yearPublished: 2020,
    country: "United States",
    category: "Documentary",
    url: "https://culturalrevolution.pitt.edu/",
    goodreads: null,
    amazon: null
  },
  {
    id: 20,
    title: "CR/10 Project – Individual Video Interviews",
    author: "Various Witnesses (CR/10 Project)",
    description: "Sample interview: a woman from Guangdong describing life 'far outside government control' and listening to Voice of America during the CR. Each interview is approximately 10 minutes with English subtitles. 300+ individual interviews archived and openly accessible.",
    yearPublished: 2015,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://digital.library.pitt.edu/islandora/object/pitt:7198590/viewer",
    goodreads: null,
    amazon: null
  },
  {
    id: 21,
    title: "Chinese Cultural Revolution Database (中国文化大革命文库)",
    author: "Various",
    description: "Contains 10,000+ items: Central Party documents, speeches by Communist leaders, official newspapers from the 1960s–1970s, Red Guard texts, and hard-to-reach archives from diverse newspapers. Updated annually. Accessible through academic institutions.",
    yearPublished: null,
    country: "China / United States",
    category: "Archival Collection",
    url: null,
    goodreads: null,
    amazon: null
  },
  {
    id: 22,
    title: "Morning Sun: A Film and Website about the Cultural Revolution",
    author: "Long Bow Group",
    description: "Documentary film with accompanying website featuring personal histories, narratives, and events related to the CR. Includes interviews and first-hand accounts.",
    yearPublished: null,
    country: "United States",
    category: "Documentary",
    url: null,
    goodreads: null,
    amazon: null
  },
  {
    id: 23,
    title: "Ten Years of Madness: Oral Histories of China's Cultural Revolution",
    author: "Feng Jicai (compiler)",
    description: "A collection of oral histories expertly conducted and arranged by renowned Chinese writer Feng Jicai. Features a diverse cross-section of individuals: intellectuals, workers, and peasants. Originally published in China in 1991.",
    yearPublished: 1991,
    country: "United States",
    category: "Oral History",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/162134.Ten_Years_of_Madness",
    amazon: "https://www.amazon.com/Ten-Years-Madness-Histories-Revolution/dp/083512584X"
  },
  {
    id: 24,
    title: "Victims of the Cultural Revolution: Testimonies of China's Tragedy",
    author: "Wang Youqin",
    description: "Based on decades of research (started 2004), this work documents deaths and testimonies of 600+ CR victims. Wang Youqin, Senior Instructional Professor at the University of Chicago, maintains a memorial website with victim testimonies.",
    yearPublished: 2008,
    country: "United States",
    category: "Oral History",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/61271867-victims-of-the-cultural-revolution",
    amazon: "https://www.amazon.com/Victims-Cultural-Revolution-Testimonies-Tragedy/dp/0861542231"
  },
  {
    id: 25,
    title: "Cultural Revolution: Testimonies of 14 Witnesses from Nanjing University",
    author: "Dong Guoqiang (compiler)",
    description: "An oral history project documenting 14 witnesses who were at Nanjing University during the Cultural Revolution. Published through Modern China Studies.",
    yearPublished: null,
    country: "United States",
    category: "Oral History",
    url: null,
    goodreads: null,
    amazon: null
  },
  {
    id: 26,
    title: "Mao's Lost Children: Stories of the Rusticated Youth of China's Cultural Revolution",
    author: "Ou Nianzhong and Liang Yongkang (eds.), trans. Laura Maynard",
    description: "A collection of memoirs from sent-down youth, including accounts from a Hainan Island state farm. Participants describe feelings of defiance and resistance.",
    yearPublished: null,
    country: "United States",
    category: "Oral History",
    url: null,
    goodreads: "https://www.goodreads.com/en/book/show/26493889-mao-s-lost-children",
    amazon: "https://www.amazon.com/Maos-Lost-Children-Rusticated-Revolution/dp/193738568X"
  },
  {
    id: 27,
    title: "The Cultural Revolution as History",
    author: "Joseph W. Esherick, Paul G. Pickowicz, Andrew G. Walder (eds.)",
    description: "A collection of research essays by graduate students who conducted extensive fieldwork, interviews, and archival research. Includes detailed grassroots accounts of CR violence and lived experience.",
    yearPublished: 2006,
    country: "United States",
    category: "Academic Collection",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/815863.The_Chinese_Cultural_Revolution_as_History",
    amazon: "https://www.amazon.com/Cultural-Revolution-Shorenstein-Asia-Pacific-Research/dp/0804753490"
  },
  {
    id: 28,
    title: "Proletarian Power: Shanghai in the Cultural Revolution",
    author: "Elizabeth L. Perry and Li Xun",
    description: "Based on extensive archival access and interviews, this work reveals Shanghai's exceptional experience during the CR compared to other cities. First-hand accounts are integrated throughout.",
    yearPublished: null,
    country: "United States",
    category: "Academic Collection",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/971635.Proletarian_Power",
    amazon: "https://www.amazon.com/Proletarian-Power-Shanghai-Revolution-Transitions-Asia/dp/0813321654"
  },
  {
    id: 29,
    title: "The Killing Wind: A Chinese County's Descent Into Madness During the Cultural Revolution",
    author: "Tan Hecheng",
    description: "A detailed account of mass killings in Dao County, Hunan Province, based on interviews and archival research. Documents how ordinary people became perpetrators of extraordinary violence during the CR.",
    yearPublished: 2017,
    country: "China / United States",
    category: "Academic Collection",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/29953708-the-killing-wind",
    amazon: "https://www.amazon.com/Killing-Wind-Chinese-Cultural-Revolution/dp/0190622520"
  },
  {
    id: 30,
    title: "A Chinese Rebel beyond the Great Wall: The Cultural Revolution and Ethnic Pogrom in Inner Mongolia",
    author: "Cheng Tiejun (TJ Cheng); eds. Uradyn E. Bulag, Mark Selden",
    description: "Cheng Tiejun provides first-person recollections of being a Red Guard in Inner Mongolia. Documents persecution of Mongol intellectuals and leaders, resulting in 16,000+ deaths.",
    yearPublished: 2023,
    country: "United States",
    category: "Academic Collection",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/123179980",
    amazon: "https://www.amazon.com/Chinese-Rebel-beyond-Great-Wall/dp/0226826848"
  },
  {
    id: 31,
    title: "Balzac and the Little Chinese Seamstress",
    author: "Dai Sijie",
    description: "A novel based on the author's personal experiences as sent-down youth during the CR. Two youths are relocated to a remote mountain village for 're-education.' Originally written in French.",
    yearPublished: 2000,
    country: "United States / France",
    category: "Literary Fiction",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/533465.Balzac_and_the_Little_Chinese_Seamstress",
    amazon: "https://www.amazon.com/Balzac-Little-Chinese-Seamstress-Novel/dp/0385722206"
  },
  {
    id: 32,
    title: "Waiting",
    author: "Ha Jin",
    description: "A National Book Award–winning novel drawing on the author's lived experience and observations during the CR era in China. The first-hand narrative is grounded in actual experiences.",
    yearPublished: 1999,
    country: "United States",
    category: "Literary Fiction",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/235773.Waiting",
    amazon: "https://www.amazon.com/Waiting-Novel-Ha-Jin/dp/0375706410"
  },
  {
    id: 33,
    title: "Do Not Say We Have Nothing",
    author: "Madeleine Thien",
    description: "A novel with significant portions set during the Cultural Revolution. Incorporates the author's family experiences during the period. Finalist for the Man Booker Prize.",
    yearPublished: 2016,
    country: "Canada / United States",
    category: "Literary Fiction",
    url: null,
    goodreads: "https://www.goodreads.com/en/book/show/31549906-do-not-say-we-have-nothing",
    amazon: "https://www.amazon.com/Do-Not-Say-Have-Nothing/dp/039360988X"
  },
  {
    id: 34,
    title: "\"My Uncle Was a Red Guard in China's Cultural Revolution. He Isn't Sorry.\"",
    author: "Foreign Policy Magazine",
    description: "First-person family interviews with an uncle nicknamed Lishui who was 18 during the CR. He expressed no regret for his actions 50 years later. Includes accounts of struggle sessions, forced confessions of grandfather, and a perpetrator's perspective.",
    yearPublished: 2016,
    country: "United States",
    category: "Journalism",
    url: "https://foreignpolicy.com/2016/05/16/my-uncle-was-a-red-guard-in-chinas-cultural-revolution-he-isnt-sorry/",
    goodreads: null,
    amazon: null
  },
  {
    id: 35,
    title: "\"A Survivor's Account of the Cultural Revolution\" (Video)",
    author: "Min Zhou (interviewed by Kristie Lu Stout)",
    description: "Min Zhou shares her experiences on camera. Her parents were sent to a labor camp when she was age 10. First-person video testimony.",
    yearPublished: 2016,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://www.youtube.com/watch?v=rieA7USjDio",
    goodreads: null,
    amazon: null
  },
  {
    id: 36,
    title: "\"Surviving China's Cultural Revolution\"",
    author: "Qijian Wang (Asian American Writers' Workshop)",
    description: "Interview with Qijian Wang, an acupuncturist in Flushing, NY. Sent to remote Da Ba Mountain village at age 16 in 1968. Documents rural labor camp experience, family separation, brother's death in camp, and denial of college admission due to father's 'traitor' status.",
    yearPublished: 2016,
    country: "United States",
    category: "Journalism",
    url: "https://aaww.org/surviving-chinas-cultural-revolution/",
    goodreads: null,
    amazon: null
  },
  {
    id: 37,
    title: "\"Confessions of a Red Guard, 50 Years after China's Cultural Revolution\"",
    author: "Anonymous Red Guard",
    description: "First-person confession from a person who became a Red Guard as a junior high school student (age 13 when CR began). Participated in violence and denunciations. Now describes guilt and personal responsibility.",
    yearPublished: 2016,
    country: "United States",
    category: "Journalism",
    url: "https://gantnews.com/2016/05/15/confessions-of-a-red-guard-50-years-after-chinas-cultural-revolution/",
    goodreads: null,
    amazon: null
  },
  {
    id: 38,
    title: "CR/10 Project – North Carolina Interviews",
    author: "Various Witnesses (UNC Library)",
    description: "UNC Library contributed interviews with CR witnesses and family members from North Carolina. Three audio/video interviews conducted in person in Cary and Chapel Hill. Some interviewees requested anonymity with still photos instead of video.",
    yearPublished: 2015,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://guides.lib.unc.edu/cul_revolution/primary",
    goodreads: null,
    amazon: null
  },
  {
    id: 39,
    title: "CR/10 Project – Woman from Anhui",
    author: "Anonymous (CR/10 Project)",
    description: "Individual video interview from the CR/10 Project. Witness: a woman from Anhui, born in the 1960s, from a military family background, a student during the CR. Part of the 300+ interview archive.",
    yearPublished: 2015,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://digital.library.pitt.edu/collection/chinas-cultural-revolution-memories-the-CR10-project",
    goodreads: null,
    amazon: null
  },
  {
    id: 40,
    title: "CR/10 Project – Man from Beijing",
    author: "Anonymous (CR/10 Project)",
    description: "Individual video interview from the CR/10 Project. Witness: a man from Beijing, born in the 1960s, from an intellectual family background, with graduate education, a student during the CR. Part of the 300+ interview archive.",
    yearPublished: 2015,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://digital.library.pitt.edu/collection/chinas-cultural-revolution-memories-the-CR10-project",
    goodreads: null,
    amazon: null
  },
  {
    id: 41,
    title: "CR/10 Project – Woman from Guangdong",
    author: "Anonymous (CR/10 Project)",
    description: "Individual video interview from the CR/10 Project. Witness: a woman from Guangdong who describes life 'far outside government control' and secretly listening to Voice of America during the Cultural Revolution. Part of the 300+ interview archive.",
    yearPublished: 2015,
    country: "United States",
    category: "Video / Oral History Collection",
    url: "https://digital.library.pitt.edu/collection/chinas-cultural-revolution-memories-the-CR10-project",
    goodreads: null,
    amazon: null
  },
  {
    id: 43,
    title: "Son of the Revolution",
    author: "Liang Heng and Judith Shapiro",
    description: "Liang Heng grew up in Changsha, Hunan, the son of a newspaper reporter father and a mother branded a 'Rightist' who was exiled to a labor camp — causing his father to divorce her to protect the family. Liang chronicles his boyhood in poverty as a 'stinking intellectual's son,' his time as a street gang member, his experience as a child Red Guard, and his years as sent-down youth in the remote countryside. Written with his American wife Judith Shapiro after emigrating in the early 1980s, it is one of the earliest and most widely read English-language memoirs of the CR, praised for its candor about both victim and perpetrator dynamics within a single family.",
    yearPublished: 1983,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/785434.Son_of_the_Revolution",
    amazon: "https://www.amazon.com/Son-Revolution-Liang-Heng/dp/0394722744"
  },
  {
    id: 44,
    title: "Blood Red Sunset: A Memoir of the Chinese Cultural Revolution",
    author: "Ma Bo",
    description: "In 1968, seventeen-year-old Ma Bo volunteered as a Red Guard sent to Inner Mongolia, where he beat and persecuted local Mongolian herdsmen with fierce ideological zeal. After casually criticizing a Party cadre, he was denounced as an 'active counterrevolutionary' by his own comrades, savagely beaten, and sentenced to labor reform. The memoir is notable for its unflinching self-indictment — Ma Bo does not spare himself in recounting his role as both perpetrator and eventual victim. First banned in China, it became one of the country's best-selling memoirs after the ban was lifted; translated by Howard Goldblatt.",
    yearPublished: 1988,
    country: "China / United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/398334.Blood_Red_Sunset",
    amazon: "https://www.amazon.com/Blood-Red-Sunset-Cultural-Revolution/dp/0140159428"
  },
  {
    id: 45,
    title: "Born Red: A Chronicle of the Cultural Revolution",
    author: "Gao Yuan",
    description: "Gao Yuan was a young teenager at a middle school in Zhangjiakou when the Cultural Revolution erupted in 1966, and his memoir covers the intense years of 1966–1969 entirely from inside the experience as he lived it. His father was a county Party official who fell in and out of political trouble, and the book's power comes from the interplay between a father navigating the system and a son caught up in Red Guard frenzy. Published by Stanford University Press in 1987 based on a memoir Gao wrote while a postgraduate student there, it is acclaimed by historians as among the most immediate and credible first-person accounts of the Red Guard period.",
    yearPublished: 1987,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/670183.Born_Red",
    amazon: "https://www.amazon.com/Born-Red-Chronicle-Cultural-Revolution/dp/0804713693"
  },
  {
    id: 46,
    title: "Spider Eaters: A Memoir",
    author: "Rae Yang",
    description: "Rae Yang grew up in a privileged diplomatic family — spending part of her childhood in Switzerland — before returning to Beijing's elite No. 101 Middle School, where she became a Red Guard. The memoir traces her path from zealous participant in struggle sessions to disillusioned laborer on a remote pig farm in China's far north, and is distinctive for its psychological honesty about the blurred line between victim and victimizer. Yang, who became a professor of Chinese literature at Dickinson College, reflects on how her generation was both shaped and destroyed by ideology. Published by University of California Press in 1997.",
    yearPublished: 1997,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/525437.Spider_Eaters",
    amazon: "https://www.amazon.com/Spider-Eaters-Memoir-Rae-Yang/dp/0520276027"
  },
  {
    id: 47,
    title: "To the Storm: The Odyssey of a Revolutionary Chinese Woman",
    author: "Yue Daiyun and Carolyn Wakeman",
    description: "Yue Daiyun was a literature professor at Peking University who had joined the Communist Party underground as a student in 1948, making her persecution during the CR a painful double betrayal. Labeled a Rightist in 1958 and targeted again during the CR along with her husband, she endured struggle sessions, forced labor, and the death of an infant son denied proper medical care because of her political status. Co-written with Berkeley scholar Carolyn Wakeman and published by University of California Press in 1985, it is one of the rare memoirs by an academic who was a true believer first and a victim second, offering unsparing reflection on complicity and survival.",
    yearPublished: 1985,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/1100650.To_The_Storm",
    amazon: "https://www.amazon.com/Storm-Daiyun-Yue/dp/0520060296"
  },
  {
    id: 48,
    title: "Red Flower of China: An Autobiography",
    author: "Zhai Zhenhua",
    description: "Born in 1951 to committed Communist parents, Zhai Zhenhua was fifteen when she enthusiastically joined the Red Guards, led raids on neighbors' homes, conducted humiliation sessions of teachers, and participated in beatings she acknowledges were fatal. When the Red Guards fell out of favor, she was purged, sent to one of the most impoverished regions of China for physical re-education labor, and eventually became one of a handful of students selected for university. Now an engineering professor in British Columbia, Zhai does not minimize her own guilt, making this one of the rare CR memoirs written squarely from a perpetrator's perspective. Originally published in Canada in 1992.",
    yearPublished: 1992,
    country: "Canada",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/1191775.Red_Flower_of_China",
    amazon: "https://www.amazon.com/Flower-China-Autobiography-Zhai-Zhenhua/dp/156947009X"
  },
  {
    id: 49,
    title: "A Leaf in the Bitter Wind: A Memoir",
    author: "Ting-xing Ye",
    description: "Born in Shanghai in 1952, Ting-xing Ye was the youngest of six children in a family branded 'bourgeois,' and was sent to a remote state farm for years of forced labor during the CR before training as an English interpreter for the Chinese government. The memoir details not only the political persecution but also the domestic violence of her first marriage and her eventual defection to Canada in 1987 after falling in love with her Canadian English teacher. Published in nine countries and a bestseller in Canada, it stands out for its dual focus on gendered suffering and political persecution in a single coherent life narrative.",
    yearPublished: 1997,
    country: "Canada",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/570927.A_Leaf_in_the_Bitter_Wind",
    amazon: "https://www.amazon.com/Leaf-Bitter-Wind-Ting-Xing-Ye/dp/0385257015"
  },
  {
    id: 50,
    title: "Bitter Winds: A Memoir of My Years in China's Gulag",
    author: "Harry Wu and Carolyn Wakeman",
    description: "On the morning after his graduation from Beijing's Geology Institute in 1960, Harry Wu — son of a Shanghai banker and deemed a class enemy — was arrested without charge and spent the next nineteen years in a series of laogai (labor reform) camps, living through starvation, torture, and the full arc of the Cultural Revolution as a prisoner. Released in 1979, Wu eventually reached the United States and became a human rights activist. Co-written with Carolyn Wakeman and published in 1994, this memoir documents the Chinese prison-camp system across the Anti-Rightist Campaign and the CR, spanning the full breadth of Maoist political persecution.",
    yearPublished: 1994,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/513724",
    amazon: "https://www.amazon.com/Bitter-Winds-Memoir-Years-Chinas/dp/0471556459"
  },
  {
    id: 51,
    title: "No Tears for Mao: Growing Up in the Cultural Revolution",
    author: "Niu Niu",
    description: "Born literally days before Mao declared the Cultural Revolution in 1966, Niu Niu was four years old when Red Guards raided her home and took both her parents — actors from a 'bourgeois' family — to a re-education camp, leaving her and her grandmother to survive on near-starvation rations. The memoir traces her entire childhood through adolescence within the CR's shadow and ends with her emigration to France, where she became an actress and filmmaker. First published in France in 1989 and in English in 1995, it is one of the few CR accounts written by someone who experienced it from literal infancy and has no memory of life before it.",
    yearPublished: 1989,
    country: "France / United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/614269.No_Tears_for_Mao",
    amazon: "https://www.amazon.com/No-Tears-Mao-Cultural-Revolution/dp/0897334930"
  },
  {
    id: 52,
    title: "Prisoner of the State: The Secret Journal of Premier Zhao Ziyang",
    author: "Zhao Ziyang (trans. and ed. Bao Pu, Renee Chiang, Adi Ignatius)",
    description: "Zhao Ziyang, the reformist General Secretary of the Chinese Communist Party purged after opposing the Tiananmen crackdown in 1989, secretly recorded his memoirs onto children's cassette tapes — recording over Peking Opera and children's music during gaps in his guards' surveillance — across more than a year of house arrest before his death in 2005. The memoir includes Zhao's first-hand account of his own persecution during the Cultural Revolution as well as his insider view of Mao's political machinations, making it a uniquely high-level primary source on CR politics. Published posthumously in 2009 after his son smuggled out the tapes, it was edited with an introduction by Roderick MacFarquhar.",
    yearPublished: 2009,
    country: "United States",
    category: "Memoir",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/6235027-prisoner-of-the-state",
    amazon: "https://www.amazon.com/Prisoner-State-Secret-Journal-Premier/dp/1439149380"
  },
  {
    id: 42,
    title: "Mao's Last Revolution",
    author: "Roderick MacFarquhar and Michael Schoenhals",
    description: "A comprehensive account incorporating extensive interviews, memoirs, and newly available documents. First-hand testimonies are integrated throughout to document Mao's political machinations and CR experiences from multiple perspectives.",
    yearPublished: 2006,
    country: "United States",
    category: "Academic Collection",
    url: null,
    goodreads: "https://www.goodreads.com/book/show/9747.Mao_s_Last_Revolution",
    amazon: "https://www.amazon.com/Maos-Last-Revolution-Roderick-MacFarquhar/dp/0674023323"
  }
];

const categories = [
  "All",
  "Memoir",
  "Oral History",
  "Video / Oral History Collection",
  "Archival Collection",
  "Documentary",
  "Academic Collection",
  "Literary Fiction",
  "Journalism"
];
